executable              = test_qcd.sh
output                  = /afs/cern.ch/user/g/gortona/work/Phase2/CMSSW_11_1_0_pre6/src/TreeMaker/Ntuplzr/$(ClusterId).out
#output/$(ClusterId).$(ProcId).out
error                   = /afs/cern.ch/user/g/gortona/work/Phase2/CMSSW_11_1_0_pre6/src/TreeMaker/Ntuplzr/error/$(ClusterId).$(ProcId).err
log                     = /afs/cern.ch/user/g/gortona/work/Phase2/CMSSW_11_1_0_pre6/src/TreeMaker/Ntuplzr/log/$(ClusterId).log
Initialdir              = /afs/cern.ch/user/g/gortona/work/Phase2/CMSSW_11_1_0_pre6/src/TreeMaker/Ntuplzr

request_memory          = 4000M
+JobFlavour             = "longlunch"

x509userproxy           = /afs/cern.ch/user/g/gortona/x509up_u49999

#https://www-auth.cs.wisc.edu/lists/htcondor-users/2010-September/msg00009.shtml
periodic_remove         = JobStatus == 5

ShouldTransferFiles     = YES
